# Catalogue Service Endpoint
catalogue.service-url=http://catalogue:5000/api/products

# Datasource - PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres-cluster-rw}:${DB_PORT:5432}/${DB_NAME:app}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:app}
spring.datasource.password=${DB_PASSWORD:}

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
