apiVersion: v1
kind: Secret
metadata:
  name: api-db-secret
type: Opaque
stringData:
  DATABASE_URL: "postgres://app:NxZCE1brARHqg9nVPmvFf71eTY5xodOCFwXKXTfBamt06oIsAK5R3ZIVciIjZZq9@postgres-restore-rw:5432/app?sslmode=disable"
